### ISSUE TITLE
Multilevel nested not indented

### ISSUE THREAD

**Issue by tacman** [MGatner/adminlte4#3]
![image](https://user-images.githubusercontent.com/619585/123474264-b19d0d00-d5c7-11eb-99c3-85fa93305401.png)

Level 2 should be indented, maybe a bit smaller, yes?

Thanks for the demo, much easier to be talking about the same thing now!

**Comment by MGatner** [comment]
This is a distribution point for AdminLTE, not the package itself. Please read the README and bring up any requests or discussions at their repo.
