### ISSUE TITLE
Support Stimulus

### ISSUE THREAD

**Issue by tacman** [MGatner/adminlte4#4]
Since jQuery is no longer required by Bootstrap 5, many themes are avoiding it as much as possible, except with tools like DataTables, where jQuery is still required.

While I like Vue, and I think React is pretty awesome, I found the learning curve too steep for most of my projects.  But StimulusJS is awesome.  I think it'd be great to use Stimulus in the demo program.  I'll contribute some example pages if you think that's a good idea.

I also like Hinclude, especially for headers and footers with content that doesn't change. Since those fragments can be cached, it's nice bonus to have smaller pages that are often easier to work with.

**Comment by MGatner** [comment]
This is a distribution point for AdminLTE, not the package itself. Please read the README and bring up any requests or discussions at their repo.
