### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by tacman** [MGatner/adminlte4#5]
I have the following in my package.json, under the "dependencies" key:

        "adminlte4": "https://github.com/mgatner/adminlte4",

But when I run yarn install (version 2) I get

➤ YN0001: │ Error: adminlte4@https://github.com/mgatner/adminlte4.git#commit=eedf49c42b956b50ad3b1c067af1175ab4cffd36: Manifest not found
    at Function.find (/home/tac/survos/projects/scorecard/.yarn/releases/yarn-2.4.2.cjs:2:325237)
    at async /home/tac/survos/projects/scorecard/.yarn/releases/yarn-2.4.2.cjs:2:147646

I think it's just a matter of adding a package.json (yarn init?).  

Thanks.

**Comment by MGatner** [comment]
This repo is a precompiled collection of assets - you will need to reference the actual AdminLTE repo for dependencies (once it is ready). 

I suppose theoretically this stub could be made to work with its own package definition (as a separate vendor?) but that isn't work I am going to do.
