### ISSUE TITLE
Update demo to latest

### ISSUE THREAD

**Issue by tacman** [MGatner/adminlte4#6]
Some classes have changed in the demo, can you please merge the latest v4 branch and republish the demo?

Or can you tell me how to do it in my fork?  Are you using your own server, or is there a way to publish it on github.io or somewhere in github?

Thanks.

**Comment by MGatner** [comment]
I will update to the latest. I would tell you how I did it but I don't precisely remember 🤣 I'll add some docs this time as well.

**Comment by MGatner** [comment]
Repo and demo (https://adminlte4.gatner.be) updated! All I did was follow the docs on the main repo so no need to duplicate the steps here.
